# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parvis_gui4.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1626, 1106)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon36.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(1600, 1080))
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.login_page)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(600, -1, 600, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lb_parvis = QtWidgets.QLabel(self.login_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_parvis.sizePolicy().hasHeightForWidth())
        self.lb_parvis.setSizePolicy(sizePolicy)
        self.lb_parvis.setMinimumSize(QtCore.QSize(300, 400))
        self.lb_parvis.setMaximumSize(QtCore.QSize(300, 400))
        self.lb_parvis.setPixmap(QtGui.QPixmap(":/newPrefix/parvis_logo.png"))
        self.lb_parvis.setScaledContents(True)
        self.lb_parvis.setObjectName("lb_parvis")
        self.horizontalLayout_7.addWidget(self.lb_parvis)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.hbox_ID = QtWidgets.QHBoxLayout()
        self.hbox_ID.setContentsMargins(-1, 50, -1, -1)
        self.hbox_ID.setSpacing(0)
        self.hbox_ID.setObjectName("hbox_ID")
        self.lb_ID = QtWidgets.QLabel(self.login_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_ID.sizePolicy().hasHeightForWidth())
        self.lb_ID.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lb_ID.setFont(font)
        self.lb_ID.setPixmap(QtGui.QPixmap(":/newPrefix/username_fix.png"))
        self.lb_ID.setScaledContents(True)
        self.lb_ID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_ID.setObjectName("lb_ID")
        self.hbox_ID.addWidget(self.lb_ID)
        self.edit_ID = QtWidgets.QLineEdit(self.login_page)
        self.edit_ID.setMinimumSize(QtCore.QSize(100, 78))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_ID.setFont(font)
        self.edit_ID.setObjectName("edit_ID")
        self.hbox_ID.addWidget(self.edit_ID)
        self.verticalLayout_3.addLayout(self.hbox_ID)
        self.hbox_PW = QtWidgets.QHBoxLayout()
        self.hbox_PW.setSpacing(0)
        self.hbox_PW.setObjectName("hbox_PW")
        self.lb_PW = QtWidgets.QLabel(self.login_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_PW.sizePolicy().hasHeightForWidth())
        self.lb_PW.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.lb_PW.setFont(font)
        self.lb_PW.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lb_PW.setPixmap(QtGui.QPixmap(":/newPrefix/password_fix.png"))
        self.lb_PW.setScaledContents(True)
        self.lb_PW.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_PW.setObjectName("lb_PW")
        self.hbox_PW.addWidget(self.lb_PW)
        self.edit_PW = QtWidgets.QLineEdit(self.login_page)
        self.edit_PW.setMinimumSize(QtCore.QSize(100, 78))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_PW.setFont(font)
        self.edit_PW.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_PW.setClearButtonEnabled(False)
        self.edit_PW.setObjectName("edit_PW")
        self.hbox_PW.addWidget(self.edit_PW)
        self.verticalLayout_3.addLayout(self.hbox_PW)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(41, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_findpw = QtWidgets.QPushButton(self.login_page)
        self.btn_findpw.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        font.setKerning(False)
        self.btn_findpw.setFont(font)
        self.btn_findpw.setFlat(True)
        self.btn_findpw.setObjectName("btn_findpw")
        self.horizontalLayout_4.addWidget(self.btn_findpw)
        self.btn_register = QtWidgets.QPushButton(self.login_page)
        self.btn_register.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.btn_register.setFont(font)
        self.btn_register.setFlat(True)
        self.btn_register.setObjectName("btn_register")
        self.horizontalLayout_4.addWidget(self.btn_register)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.login_page)
        self.search_page = QtWidgets.QWidget()
        self.search_page.setObjectName("search_page")
        self.gridLayout = QtWidgets.QGridLayout(self.search_page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(200, 50, 200, 50)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(100, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo = QtWidgets.QLabel(self.search_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(300, 410))
        self.logo.setPixmap(QtGui.QPixmap(":/newPrefix/parvis_face.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.horizontalLayout_3.addWidget(self.logo)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(350, 100, 237, 50)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_search = QtWidgets.QLabel(self.search_page)
        self.lb_search.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_search.sizePolicy().hasHeightForWidth())
        self.lb_search.setSizePolicy(sizePolicy)
        self.lb_search.setMaximumSize(QtCore.QSize(80, 80))
        self.lb_search.setPixmap(QtGui.QPixmap(":/newPrefix/search.png"))
        self.lb_search.setScaledContents(True)
        self.lb_search.setObjectName("lb_search")
        self.horizontalLayout.addWidget(self.lb_search)
        self.edit_search = QtWidgets.QLineEdit(self.search_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_search.sizePolicy().hasHeightForWidth())
        self.edit_search.setSizePolicy(sizePolicy)
        self.edit_search.setMinimumSize(QtCore.QSize(500, 80))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.edit_search.setFont(font)
        self.edit_search.setObjectName("edit_search")
        self.horizontalLayout.addWidget(self.edit_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(100, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.statusbar = QtWidgets.QLabel(self.search_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setPixmap(QtGui.QPixmap(":/newPrefix/statusbar_before enter.png"))
        self.statusbar.setScaledContents(True)
        self.statusbar.setObjectName("statusbar")
        self.horizontalLayout_5.addWidget(self.statusbar)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.search_page)
        self.result_page = QtWidgets.QWidget()
        self.result_page.setObjectName("result_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.result_page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(50, -1, 50, 100)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 50, -1, -1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lb_rsearch = QtWidgets.QLabel(self.result_page)
        self.lb_rsearch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_rsearch.sizePolicy().hasHeightForWidth())
        self.lb_rsearch.setSizePolicy(sizePolicy)
        self.lb_rsearch.setMaximumSize(QtCore.QSize(80, 80))
        self.lb_rsearch.setPixmap(QtGui.QPixmap(":/newPrefix/search.png"))
        self.lb_rsearch.setScaledContents(True)
        self.lb_rsearch.setObjectName("lb_rsearch")
        self.horizontalLayout_6.addWidget(self.lb_rsearch)
        self.edit_rsearch = QtWidgets.QLineEdit(self.result_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_rsearch.sizePolicy().hasHeightForWidth())
        self.edit_rsearch.setSizePolicy(sizePolicy)
        self.edit_rsearch.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.edit_rsearch.setFont(font)
        self.edit_rsearch.setObjectName("edit_rsearch")
        self.horizontalLayout_6.addWidget(self.edit_rsearch)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.layout_mword = QtWidgets.QGridLayout()
        self.layout_mword.setContentsMargins(-1, 20, -1, -1)
        self.layout_mword.setObjectName("layout_mword")
        self.verticalLayout_2.addLayout(self.layout_mword)
        self.textBrowser = QtWidgets.QTextBrowser(self.result_page)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.tableWidget = QtWidgets.QTableWidget(self.result_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.btn_IPC = QtWidgets.QPushButton(self.result_page)
        self.btn_IPC.setObjectName("btn_IPC")
        self.verticalLayout_2.addWidget(self.btn_IPC)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.result_page)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Parvis"))
        self.edit_ID.setPlaceholderText(_translate("MainWindow", "Username"))
        self.edit_PW.setPlaceholderText(_translate("MainWindow", "Password"))
        self.btn_findpw.setText(_translate("MainWindow", "비밀번호 찾기 |"))
        self.btn_register.setText(_translate("MainWindow", "회원가입                      "))
        self.btn_IPC.setText(_translate("MainWindow", "IPC 제거"))

import parvis_rc

class Ui_check_mword(object):
    def setupUi(self, check_mword):
        check_mword.setObjectName("check_mword")
        check_mword.setMaximumSize(QtCore.QSize(150, 200))
        self.horizontalLayout = QtWidgets.QHBoxLayout(check_mword)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(check_mword)
        self.scrollArea.setMinimumSize(QtCore.QSize(1, 1))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 123, 168))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(check_mword)
        QtCore.QMetaObject.connectSlotsByName(check_mword)

    def retranslateUi(self, check_mword):
        _translate = QtCore.QCoreApplication.translate
        check_mword.setWindowTitle(_translate("check_mword", "Form"))


